[tool.poetry]
name = "pcap2p4"
version = "0.1.0"
description = ""
authors = ["trvon <git@trevon.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
scapy = "^2.6.0"
networkx = "^3.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
